language: java

dist: trusty

sudo: required

jdk:
  - oraclejdk8
  - openjdk8

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx2048m"
 - "echo $JAVA_OPTS"
 - "ulimit -a"
 - "ulimit -u 2048"
 - "ulimit -a"
 - "umask 022"
 - "mkdir inputs"

cache:
  directories:
  - $HOME/.m2

notifications:
  slack: ukwebarchive:oqbYOo0bd09bnSXn4hGR1aUk

after_success:
  - bash <(curl -s https://codecov.io/bash)
